name: dart_sdk_issue_45003_reproduction
description: Dart SDK issue 45003 reproduction
version: 1.0.0
homepage: https://github.com/dart-lang/sdk/issues/45003

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  freezed_annotation: ^0.14.1
  counting_set:
    git:
      url: 'git://github.com/hacker1024/counting_set.dart.git'
      ref: '3e1353cde9e45ffce4acf8156a06cdf0061e1219'

dev_dependencies:
  build_runner: ^1.12.2
  freezed: 0.14.1+2